# Generated by Django 4.2.1 on 2023-06-08 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('user', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tur',
            fields=[
                ('id_tur', models.IntegerField(primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=30, verbose_name='Город')),
                ('designation', models.CharField(max_length=200, verbose_name='Название')),
                ('data', models.DateTimeField(verbose_name='Дата')),
                ('descrition', models.TextField(max_length=5000, verbose_name='Описание')),
                ('amount', models.IntegerField(verbose_name='количество дней')),
                ('accompanying', models.CharField(max_length=30, verbose_name='Сопровождающий')),
                ('image', models.ImageField(upload_to='turs/', verbose_name='Фотография')),
            ],
        ),
        migrations.CreateModel(
            name='Users_type',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30, verbose_name='Пароль')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('parse_id', models.IntegerField()),
                ('email', models.EmailField(max_length=200, verbose_name='Электронная почта')),
                ('password', models.CharField(max_length=30, verbose_name='Пароль')),
                ('logged_in', models.BooleanField()),
                ('user_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.users_type')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('text', models.TextField(max_length=5000, verbose_name='Отзыв')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.reviews', verbose_name='')),
                ('tur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.tur', verbose_name='Тур')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('socNetwork', models.CharField(max_length=30, verbose_name='Соц.Сеть')),
                ('id_tura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.tur')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.users')),
            ],
        ),
    ]
