# Generated by Django 4.2.1 on 2023-06-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tur_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tur',
            name='url',
            field=models.SlugField( max_length=160, unique=True),
            preserve_default=False,
        ),
    ]
