# Generated by Django 4.2.1 on 2023-06-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tur_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tur',
            name='url',
        ),
    ]
